/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListIpGroupsRequest struct {
	Marker      *string  `json:"marker,omitempty"`
	Limit       *int32   `json:"limit,omitempty"`
	PageReverse *bool    `json:"page_reverse,omitempty"`
	Id          []string `json:"id,omitempty"`
	Name        []string `json:"name,omitempty"`
	Description []string `json:"description,omitempty"`
	IpList      []string `json:"ip_list,omitempty"`
}

func (o ListIpGroupsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListIpGroupsRequest", string(data)}, " ")
}
