/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowLoadBalancerStatusResponse struct {
	Statuses *LoadBalancerStatusResult `json:"statuses,omitempty"`
}

func (o ShowLoadBalancerStatusResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowLoadBalancerStatusResponse", string(data)}, " ")
}
