/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type DeleteL7RuleResponse struct {
}

func (o DeleteL7RuleResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteL7RuleResponse", string(data)}, " ")
}
