/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type RuleRef struct {
	// 规则ID。
	Id string `json:"id"`
}

func (o RuleRef) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"RuleRef", string(data)}, " ")
}
