/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowIpGroupResponse struct {
	Ipgroup *IpGroup `json:"ipgroup,omitempty"`
}

func (o ShowIpGroupResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowIpGroupResponse", string(data)}, " ")
}
