/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 负载均衡器信息
type LoadBalancerRef struct {
	// 负载均衡器ID。
	Id *string `json:"id,omitempty"`
}

func (o LoadBalancerRef) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"LoadBalancerRef", string(data)}, " ")
}
