/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DeleteL7PolicyRequest struct {
	L7policyId string `json:"l7policy_id"`
}

func (o DeleteL7PolicyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteL7PolicyRequest", string(data)}, " ")
}
