/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListCertificatesResponse struct {
	// 请求ID。 注：自动生成 。
	RequestId *string   `json:"request_id,omitempty"`
	PageInfo  *PageInfo `json:"page_info,omitempty"`
	// 证书对象列表。
	Certificates *[]Certificate `json:"certificates,omitempty"`
}

func (o ListCertificatesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListCertificatesResponse", string(data)}, " ")
}
