/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListPoolsRequest struct {
	Marker                         *string  `json:"marker,omitempty"`
	Limit                          *int32   `json:"limit,omitempty"`
	PageReverse                    *bool    `json:"page_reverse,omitempty"`
	Description                    []string `json:"description,omitempty"`
	AdminStateUp                   *bool    `json:"admin_state_up,omitempty"`
	HealthmonitorId                []string `json:"healthmonitor_id,omitempty"`
	Id                             []string `json:"id,omitempty"`
	Name                           []string `json:"name,omitempty"`
	LoadbalancerId                 []string `json:"loadbalancer_id,omitempty"`
	Protocol                       []string `json:"protocol,omitempty"`
	LbAlgorithm                    []string `json:"lb_algorithm,omitempty"`
	EnterpriseProjectId            []string `json:"enterprise_project_id,omitempty"`
	IpVersion                      []string `json:"ip_version,omitempty"`
	MemberAddress                  []string `json:"member_address,omitempty"`
	MemberDeviceId                 []string `json:"member_device_id,omitempty"`
	MemberDeletionProtectionEnable *bool    `json:"member_deletion_protection_enable,omitempty"`
}

func (o ListPoolsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListPoolsRequest", string(data)}, " ")
}
