/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowQuotaRequest struct {
}

func (o ShowQuotaRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowQuotaRequest", string(data)}, " ")
}
