/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateL7PolicyResponse struct {
	// 请求ID。  注：自动生成 。
	RequestId *string   `json:"request_id,omitempty"`
	L7policy  *L7Policy `json:"l7policy,omitempty"`
}

func (o UpdateL7PolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateL7PolicyResponse", string(data)}, " ")
}
