/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 翻页信息
type PageInfo struct {
	// 分页查询中上页的ID
	PreviousMarker string `json:"previous_marker"`
	// 分页查询中下页的ID。 注：分页的场合输出该字段。
	NextMarker *string `json:"next_marker,omitempty"`
	// 当前的记录数。
	CurrentCount int32 `json:"current_count"`
}

func (o PageInfo) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"PageInfo", string(data)}, " ")
}
