/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type PoolRef struct {
	// 功能描述：后端服务器组ID。
	Id string `json:"id"`
}

func (o PoolRef) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"PoolRef", string(data)}, " ")
}
