/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListCertificatesRequest struct {
	Marker       *string   `json:"marker,omitempty"`
	Limit        *int32    `json:"limit,omitempty"`
	PageReverse  *bool     `json:"page_reverse,omitempty"`
	Id           *[]string `json:"id,omitempty"`
	Name         *[]string `json:"name,omitempty"`
	Description  *[]string `json:"description,omitempty"`
	AdminStateUp *bool     `json:"admin_state_up,omitempty"`
	Domain       *[]string `json:"domain,omitempty"`
	Type         *[]string `json:"type,omitempty"`
}

func (o ListCertificatesRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListCertificatesRequest", string(data)}, " ")
}
