/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 视图链接。
type Links struct {
	// 域名
	Href string `json:"href"`
	// 域名描述
	Rel string `json:"rel"`
}
