/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type GlanceDeleteImageRequest struct {
	ImageId string                        `json:"image_id"`
	Body    *GlanceDeleteImageRequestBody `json:"body,omitempty"`
}

func (o GlanceDeleteImageRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"GlanceDeleteImageRequest", string(data)}, " ")
}
