/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// quota响应
type Quota struct {
	// 查询的配额信息。
	Resources []QuotaInfo `json:"resources"`
}

func (o Quota) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"Quota", string(data)}, " ")
}
