/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type UpdateImageRequest struct {
	ImageId string                   `json:"image_id"`
	Body    []UpdateImageRequestBody `json:"body,omitempty"`
}

func (o UpdateImageRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateImageRequest", string(data)}, " ")
}
