/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 请求参数
type AddOrUpdateTagsRequestBody struct {
	// 镜像ID。
	ImageId string `json:"image_id"`
	// 标签数据。 tag和image_tag只能使用一个。
	Tag string `json:"tag,omitempty"`
	ImageTag *ResourceTag `json:"image_tag,omitempty"`
}
