/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type CopyImageCrossRegionResponse struct {
	// 异步任务ID。
	JobId string `json:"job_id,omitempty"`
}
