/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 镜像导出请求体
type ExportImageRequestBody struct {
	// 目的文件的URL，格式：<bucket>:<file>。 说明：此处的OBS桶和镜像文件的存储类别必须是OBS标准存储。
	BucketUrl string `json:"bucket_url"`
	// 文件格式，支持qcow2、vhd、zvhd和vmdk。
	FileFormat string `json:"file_format"`
}
