/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type GlanceDeleteImageRequest struct {
	ImageId string `json:"image_id"`
	Body *GlanceDeleteImageRequestBody `json:"body,omitempty"`
}
