/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 添加镜像成员请求参数
type GlanceAddImageMemberRequestBody struct {
	// 镜像成员。取值为目标用户的项目ID。
	Member string `json:"member"`
}
