/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CreateImageRequest struct {
	Body *CreateImageRequestBody `json:"body,omitempty"`
}
