/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 扩展更新镜像接口请求体
type UpdateImageRequestBody struct {
	// 操作类型，目前取值为add，replace和remove。
	Op string `json:"op"`
	// 需要更新的属性名称，需要在属性名称前加“/”。
	Path string `json:"path"`
	// 需要更新属性的值。
	Value string `json:"value,omitempty"`
}
