/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type ListTagsResponse struct {
	// 标签列表
	Tags []string `json:"tags,omitempty"`
}

func (o ListTagsResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListTagsResponse", string(data)}, " ")
}
