/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 镜像标签
type TagKeyValue struct {
	// 标签的键
	Key string `json:"key"`
	// 标签的值
	Value string `json:"value"`
}
