/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListTagsResponse struct {
	// 标签列表
	Tags []string `json:"tags,omitempty"`
}
