/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListImagesResponse struct {
	// 镜像列表
	Images []ImageInfo `json:"images,omitempty"`
}

func (o ListImagesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListImagesResponse", string(data)}, " ")
}
