/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type GlanceListImageMembersResponse struct {
	// 成员信息
	Members []GlanceImageMembers `json:"members,omitempty"`
	// 视图信息
	Schema string `json:"schema,omitempty"`
}
