/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListTagsRequest struct {
	Limit int32 `json:"limit,omitempty"`
	Page int32 `json:"page,omitempty"`
	Imagetype string `json:"__imagetype,omitempty"`
	Id string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Name string `json:"name,omitempty"`
	MinDisk int32 `json:"min_disk,omitempty"`
	Platform string `json:"__platform,omitempty"`
	OsType string `json:"__os_type,omitempty"`
	MemberStatus string `json:"member_status,omitempty"`
	VirtualEnvType string `json:"virtual_env_type,omitempty"`
	EnterpriseProjectId string `json:"enterprise_project_id,omitempty"`
	Architecture string `json:"architecture,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
