/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type ImportImageQuickRequest struct {
	Body *QuickImportImageByFileRequestBody `json:"body,omitempty"`
}

func (o ImportImageQuickRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ImportImageQuickRequest", string(data)}, " ")
}
