/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type RegisterImageRequest struct {
	ImageId string                    `json:"image_id"`
	Body    *RegisterImageRequestBody `json:"body,omitempty"`
}

func (o RegisterImageRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"RegisterImageRequest", string(data)}, " ")
}
