/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type GlanceShowImageMemberRequest struct {
	ImageId  string `json:"image_id"`
	MemberId string `json:"member_id"`
}

func (o GlanceShowImageMemberRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"GlanceShowImageMemberRequest", string(data)}, " ")
}
