/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type GlanceDeleteImageMemberResponse struct {
}

func (o GlanceDeleteImageMemberResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"GlanceDeleteImageMemberResponse", string(data)}, " ")
}
