/*
    * IMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type GlanceDeleteTagRequest struct {
	ImageId string `json:"image_id"`
	Tag string `json:"tag"`
}
