/*
 * IMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type GlanceDeleteTagRequest struct {
	ImageId string `json:"image_id"`
	Tag     string `json:"tag"`
}

func (o GlanceDeleteTagRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"GlanceDeleteTagRequest", string(data)}, " ")
}
