/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type ScopedTokenIdentity struct {
	// 认证方法，该字段内容为“token”。
	Methods []string     `json:"methods"`
	Token   *ScopedToken `json:"token"`
}

func (o ScopedTokenIdentity) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ScopedTokenIdentity", string(data)}, " ")
}
