/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type CreatePermanentAccessKeyRequest struct {
	Body *CreatePermanentAccessKeyRequestBody `json:"body,omitempty"`
}

func (o CreatePermanentAccessKeyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreatePermanentAccessKeyRequest", string(data)}, " ")
}
