/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type ListCustomPoliciesRequest struct {
}

func (o ListCustomPoliciesRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListCustomPoliciesRequest", string(data)}, " ")
}
