/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type UpdatePermanentAccessKeyResponse struct {
	Credential *UpdateCredentialResult `json:"credential,omitempty"`
}

func (o UpdatePermanentAccessKeyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdatePermanentAccessKeyResponse", string(data)}, " ")
}
