/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type UpdateProjectStatusResponse struct {
}

func (o UpdateProjectStatusResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateProjectStatusResponse", string(data)}, " ")
}
