/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateMetadataRequest struct {
	IdpId      string                     `json:"idp_id"`
	ProtocolId string                     `json:"protocol_id"`
	Body       *CreateMetadataRequestBody `json:"body,omitempty"`
}

func (o CreateMetadataRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateMetadataRequest", string(data)}, " ")
}
