/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type CreateMfaDeviceReq struct {
	VirtualMfaDevice *CreateMfaDevice `json:"virtual_mfa_device"`
}

func (o CreateMfaDeviceReq) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateMfaDeviceReq", string(data)}, " ")
}
