/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneDeleteGroupRequest struct {
	GroupId string `json:"group_id"`
}
