/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type KeystoneCreateUserTokenByPasswordRequestBody struct {
	Auth *PwdAuth `json:"auth"`
}

func (o KeystoneCreateUserTokenByPasswordRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneCreateUserTokenByPasswordRequestBody", string(data)}, " ")
}
