/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

//
type KeystoneUpdateUserByAdminRequestBody struct {
	User *KeystoneUpdateUserOption `json:"user"`
}

func (o KeystoneUpdateUserByAdminRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneUpdateUserByAdminRequestBody", string(data)}, " ")
}
