/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type ProtocolOption struct {
	// 映射ID。
	MappingId string `json:"mapping_id"`
}

func (o ProtocolOption) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ProtocolOption", string(data)}, " ")
}
