/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type UpdateDomainProtectPolicyRequest struct {
	DomainId string                                `json:"domain_id"`
	Body     *UpdateDomainProtectPolicyRequestBody `json:"body,omitempty"`
}

func (o UpdateDomainProtectPolicyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateDomainProtectPolicyRequest", string(data)}, " ")
}
