/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneListPermissionsRequest struct {
	Name string `json:"name,omitempty"`
}
