/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type KeystoneShowMappingResponse struct {
	Mapping *MappingResult `json:"mapping,omitempty"`
}

func (o KeystoneShowMappingResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowMappingResponse", string(data)}, " ")
}
