/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type ShowUserResponse struct {
	User *ShowUserResult `json:"user,omitempty"`
}

func (o ShowUserResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowUserResponse", string(data)}, " ")
}
