/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneCreateAgencyTokenRequest struct {
	Nocatalog *string                               `json:"nocatalog,omitempty"`
	Body      *KeystoneCreateAgencyTokenRequestBody `json:"body,omitempty"`
}

func (o KeystoneCreateAgencyTokenRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneCreateAgencyTokenRequest", string(data)}, " ")
}
