/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type UpdateDomainPasswordPolicyRequestBody struct {
	PasswordPolicy *PasswordPolicyOption `json:"password_policy"`
}

func (o UpdateDomainPasswordPolicyRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateDomainPasswordPolicyRequestBody", string(data)}, " ")
}
