/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type OsfederationProtocol struct {
	// 协议ID。
	Id string `json:"id"`
}

func (o OsfederationProtocol) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"OsfederationProtocol", string(data)}, " ")
}
