/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateUnscopeTokenByIdpInitiatedRequest struct {
	XIdpId string       `json:"X-Idp-Id"`
	Body   *interface{} `json:"body,omitempty"`
}

func (o CreateUnscopeTokenByIdpInitiatedRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateUnscopeTokenByIdpInitiatedRequest", string(data)}, " ")
}
