/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type UpdateCloudServiceCustomPolicyRequest struct {
	RoleId string                                     `json:"role_id"`
	Body   *UpdateCloudServiceCustomPolicyRequestBody `json:"body,omitempty"`
}

func (o UpdateCloudServiceCustomPolicyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateCloudServiceCustomPolicyRequest", string(data)}, " ")
}
