/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type KeystoneShowRegionResponse struct {
	Region *Region `json:"region,omitempty"`
}

func (o KeystoneShowRegionResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowRegionResponse", string(data)}, " ")
}
