/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneListEndpointsRequest struct {
	Interface KeystoneListEndpointsRequestInterface `json:"interface,omitempty"`
	ServiceId string                                `json:"service_id,omitempty"`
}

func (o KeystoneListEndpointsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListEndpointsRequest", string(data)}, " ")
}

type KeystoneListEndpointsRequestInterface struct {
	value string
}

type KeystoneListEndpointsRequestInterfaceEnum struct {
	PUBLIC   KeystoneListEndpointsRequestInterface
	INTERNAL KeystoneListEndpointsRequestInterface
	ADMIN    KeystoneListEndpointsRequestInterface
}

func GetKeystoneListEndpointsRequestInterfaceEnum() KeystoneListEndpointsRequestInterfaceEnum {
	return KeystoneListEndpointsRequestInterfaceEnum{
		PUBLIC: KeystoneListEndpointsRequestInterface{
			value: "public",
		},
		INTERNAL: KeystoneListEndpointsRequestInterface{
			value: "internal",
		},
		ADMIN: KeystoneListEndpointsRequestInterface{
			value: "admin",
		},
	}
}

func (c KeystoneListEndpointsRequestInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *KeystoneListEndpointsRequestInterface) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
