/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type KeystoneListServicesResponse struct {
	// 服务信息列表。
	Services []Service `json:"services,omitempty"`
	Links *Links `json:"links,omitempty"`
}
