/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type LinksSelf struct {
	// 资源链接地址。
	Self string `json:"self"`
}
