/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowDomainLoginPolicyResponse struct {
	LoginPolicy    *LoginPolicyResult `json:"login_policy,omitempty"`
	HttpStatusCode int                `json:"-"`
}

func (o ShowDomainLoginPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowDomainLoginPolicyResponse", string(data)}, " ")
}
