/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneShowEndpointRequest struct {
	EndpointId string `json:"endpoint_id"`
}

func (o KeystoneShowEndpointRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowEndpointRequest", string(data)}, " ")
}
