/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateUserRequest struct {
	Body *CreateUserRequestBody `json:"body,omitempty"`
}

func (o CreateUserRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateUserRequest", string(data)}, " ")
}
