/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneListProtocolsRequest struct {
	IdpId string `json:"idp_id"`
}

func (o KeystoneListProtocolsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListProtocolsRequest", string(data)}, " ")
}
