/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type UpdateUserInformationRequest struct {
	UserId string                            `json:"user_id"`
	Body   *UpdateUserInformationRequestBody `json:"body,omitempty"`
}

func (o UpdateUserInformationRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateUserInformationRequest", string(data)}, " ")
}
