/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type KeystoneCreateUserResponse struct {
	User *KeystoneCreateUserResult `json:"user,omitempty"`
}

func (o KeystoneCreateUserResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneCreateUserResponse", string(data)}, " ")
}
