/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type KeystoneUpdateProjectResponse struct {
	Project *KeystoneUpdateProjectResult `json:"project,omitempty"`
}

func (o KeystoneUpdateProjectResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneUpdateProjectResponse", string(data)}, " ")
}
