/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneUpdateUserPasswordRequest struct {
	UserId string `json:"user_id"`
	Body *KeystoneUpdateUserPasswordRequestBody `json:"body,omitempty"`
}
