/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneListProjectPermissionsForGroupRequest struct {
	ProjectId string `json:"project_id"`
	GroupId string `json:"group_id"`
}
