/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type Service struct {
	// 服务名。
	Name string `json:"name"`
	// 服务描述信息。
	Description string `json:"description,omitempty"`
	Links *Links `json:"links"`
	// 服务ID。
	Id string `json:"id"`
	// 服务类型。
	Type string `json:"type"`
	// 服务是否可用。
	Enabled bool `json:"enabled"`
}
