/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type DeleteDomainGroupInheritedRoleResponse struct {
	HttpStatusCode int `json:"-"`
}

func (o DeleteDomainGroupInheritedRoleResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteDomainGroupInheritedRoleResponse", string(data)}, " ")
}
