/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListCustomPoliciesResponse struct {
	Links *Links `json:"links,omitempty"`
	// 自定义策略信息列表。
	Roles []PolicyRoleResult `json:"roles,omitempty"`
}
