/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type KeystoneUpdateMappingRequestBody struct {
	Mapping *MappingOption `json:"mapping"`
}

func (o KeystoneUpdateMappingRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneUpdateMappingRequestBody", string(data)}, " ")
}
