/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type TokenAuth struct {
	Identity *TokenAuthIdentity `json:"identity"`
}
