/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type CreateAgencyRequestBody struct {
	Agency *CreateAgencyOption `json:"agency"`
}
