/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateAgencyCustomPolicyResponse struct {
	Role           *AgencyPolicyRoleResult `json:"role,omitempty"`
	HttpStatusCode int                     `json:"-"`
}

func (o UpdateAgencyCustomPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateAgencyCustomPolicyResponse", string(data)}, " ")
}
