/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneShowServiceRequest struct {
	ServiceId string `json:"service_id"`
}
