/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ShowCustomPolicyRequest struct {
	RoleId string `json:"role_id"`
}
