/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListAgenciesRequest struct {
	TrustDomainId string `json:"trust_domain_id,omitempty"`
	Name string `json:"name,omitempty"`
}
