/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type OsfederationGroups struct {
	// 用户组ID。
	Id string `json:"id"`
	// 用户组名称。
	Name string `json:"name"`
}

func (o OsfederationGroups) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"OsfederationGroups", string(data)}, " ")
}
