/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowUserMfaDeviceRequest struct {
	UserId string `json:"user_id"`
}

func (o ShowUserMfaDeviceRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowUserMfaDeviceRequest", string(data)}, " ")
}
