/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateMetadataResponse struct {
	// 导入结果信息。
	Message *string `json:"message,omitempty"`
}

func (o CreateMetadataResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateMetadataResponse", string(data)}, " ")
}
