/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type Links struct {
	// 资源链接地址。
	Self string `json:"self"`
	// 前一邻接资源链接地址。
	Previous string `json:"previous"`
	// 后一邻接资源链接地址。
	Next string `json:"next"`
}
