/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneCreateGroupRequest struct {
	Body *KeystoneCreateGroupRequestBody `json:"body,omitempty"`
}
