/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type UpdateAgencyResponse struct {
	Agency *AgencyResult `json:"agency,omitempty"`
}
