/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

//
type UpdateUserInformationRequestBody struct {
	User *UpdateUserInformationOption `json:"user"`
}

func (o UpdateUserInformationRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateUserInformationRequestBody", string(data)}, " ")
}
