/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type KeystoneListProjectsResponse struct {
	Links *Links `json:"links,omitempty"`
	// 项目信息列表。
	Projects []ProjectResult `json:"projects,omitempty"`
}
