/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type UpdateAgencyRequest struct {
	AgencyId string                   `json:"agency_id"`
	Body     *UpdateAgencyRequestBody `json:"body,omitempty"`
}

func (o UpdateAgencyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateAgencyRequest", string(data)}, " ")
}
