/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

//
type CreateUserRequestBody struct {
	User *CreateUserOption `json:"user"`
}

func (o CreateUserRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateUserRequestBody", string(data)}, " ")
}
