/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListUserLoginProtectsRequest struct {
}

func (o ListUserLoginProtectsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListUserLoginProtectsRequest", string(data)}, " ")
}
