/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type MfaTotp struct {
	User *MfaTotpUser `json:"user"`
}

func (o MfaTotp) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"MfaTotp", string(data)}, " ")
}
