/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneUpdateGroupRequest struct {
	GroupId string `json:"group_id"`
	Body *KeystoneUpdateGroupRequestBody `json:"body,omitempty"`
}
