/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateAgencyResponse struct {
	Agency *AgencyResult `json:"agency,omitempty"`
}

func (o CreateAgencyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateAgencyResponse", string(data)}, " ")
}
