/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListDomainPermissionsForAgencyResponse struct {
	// 权限信息列表。
	Roles []RoleResult `json:"roles,omitempty"`
}
