/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type UpdateDomainLoginPolicyRequestBody struct {
	LoginPolicy *LoginPolicyOption `json:"login_policy"`
}

func (o UpdateDomainLoginPolicyRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateDomainLoginPolicyRequestBody", string(data)}, " ")
}
