/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

//
type UpdateCredentialOption struct {
	// 访问密钥状态。取值为：“active”（启用）或者 “inactive”（停用）。status与description至少填写一个。
	Status UpdateCredentialOptionStatus `json:"status,omitempty"`
	// 访问密钥描述信息。status与description至少填写一个。
	Description *string `json:"description,omitempty"`
}

func (o UpdateCredentialOption) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateCredentialOption", string(data)}, " ")
}

type UpdateCredentialOptionStatus struct {
	value string
}

type UpdateCredentialOptionStatusEnum struct {
	ACTIVE   UpdateCredentialOptionStatus
	INACTIVE UpdateCredentialOptionStatus
}

func GetUpdateCredentialOptionStatusEnum() UpdateCredentialOptionStatusEnum {
	return UpdateCredentialOptionStatusEnum{
		ACTIVE: UpdateCredentialOptionStatus{
			value: "active",
		},
		INACTIVE: UpdateCredentialOptionStatus{
			value: "inactive",
		},
	}
}

func (c UpdateCredentialOptionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *UpdateCredentialOptionStatus) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
