/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type ShowCustomPolicyResponse struct {
	Role *PolicyRoleResult `json:"role,omitempty"`
}

func (o ShowCustomPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowCustomPolicyResponse", string(data)}, " ")
}
