/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateCloudServiceCustomPolicyResponse struct {
	Role *ServicePolicyRoleResult `json:"role,omitempty"`
}

func (o CreateCloudServiceCustomPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateCloudServiceCustomPolicyResponse", string(data)}, " ")
}
