/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type KeystoneShowEndpointResponse struct {
	Endpoint *Endpoint `json:"endpoint,omitempty"`
}
