/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type UpdateDomainProtectPolicyRequestBody struct {
	ProtectPolicy *ProtectPolicyOption `json:"protect_policy"`
}

func (o UpdateDomainProtectPolicyRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateDomainProtectPolicyRequestBody", string(data)}, " ")
}
