/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type MfaAuth struct {
	Identity *MfaIdentity `json:"identity"`
	Scope    *AuthScope   `json:"scope"`
}

func (o MfaAuth) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"MfaAuth", string(data)}, " ")
}
