/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type RemoveAllProjectsPermissionFromAgencyRequest struct {
	AgencyId string `json:"agency_id"`
	DomainId string `json:"domain_id"`
	RoleId   string `json:"role_id"`
}

func (o RemoveAllProjectsPermissionFromAgencyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"RemoveAllProjectsPermissionFromAgencyRequest", string(data)}, " ")
}
