/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowDomainConsoleAclPolicyResponse struct {
	ConsoleAclPolicy *AclPolicyResult `json:"console_acl_policy,omitempty"`
}

func (o ShowDomainConsoleAclPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowDomainConsoleAclPolicyResponse", string(data)}, " ")
}
