/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type KeystoneShowSecurityComplianceByOptionResponse struct {
	Config *ConfigByOption `json:"config,omitempty"`
}

func (o KeystoneShowSecurityComplianceByOptionResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowSecurityComplianceByOptionResponse", string(data)}, " ")
}
