/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneShowRegionRequest struct {
	RegionId string `json:"region_id"`
}

func (o KeystoneShowRegionRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowRegionRequest", string(data)}, " ")
}
