/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type RemoveDomainPermissionFromAgencyRequest struct {
	AgencyId string `json:"agency_id"`
	RoleId   string `json:"role_id"`
}

func (o RemoveDomainPermissionFromAgencyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"RemoveDomainPermissionFromAgencyRequest", string(data)}, " ")
}
