/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneCreateProtocolRequest struct {
	IdpId      string                             `json:"idp_id"`
	ProtocolId string                             `json:"protocol_id"`
	Body       *KeystoneCreateProtocolRequestBody `json:"body,omitempty"`
}

func (o KeystoneCreateProtocolRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneCreateProtocolRequest", string(data)}, " ")
}
