/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type KeystoneListGroupsResponse struct {
	// 用户组信息列表。
	Groups []KeystoneGroupResult `json:"groups,omitempty"`
	Links *Links `json:"links,omitempty"`
}
