/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneCreateUserRequest struct {
	Body *KeystoneCreateUserRequestBody `json:"body,omitempty"`
}

func (o KeystoneCreateUserRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneCreateUserRequest", string(data)}, " ")
}
