/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type TokenSocpeOption struct {
	Domain  *ScopeDomainOption  `json:"domain,omitempty"`
	Project *ScopeProjectOption `json:"project,omitempty"`
}

func (o TokenSocpeOption) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"TokenSocpeOption", string(data)}, " ")
}
