/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type KeystoneListAuthDomainsResponse struct {
	// 账号信息列表。
	Domains []Domains  `json:"domains,omitempty"`
	Links   *LinksSelf `json:"links,omitempty"`
}

func (o KeystoneListAuthDomainsResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListAuthDomainsResponse", string(data)}, " ")
}
