/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type LoginTokenDomain struct {
	// 被委托方用户所属账号名称。
	Name *string `json:"name,omitempty"`
	// 被委托方用户所属账号ID。
	Id *string `json:"id,omitempty"`
}

func (o LoginTokenDomain) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"LoginTokenDomain", string(data)}, " ")
}
