/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ShowPermanentAccessKeyRequest struct {
	AccessKey string `json:"access_key"`
}
