/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type CreateCloudServiceCustomPolicyResponse struct {
	Role *ServicePolicyRoleResult `json:"role,omitempty"`
}
