/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type KeystoneListUsersResponse struct {
	Links *Links `json:"links,omitempty"`
	// IAM用户信息列表。
	Users *[]KeystoneListUsersResult `json:"users,omitempty"`
}

func (o KeystoneListUsersResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListUsersResponse", string(data)}, " ")
}
