/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneListVersionsRequest struct {
}

func (o KeystoneListVersionsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListVersionsRequest", string(data)}, " ")
}
