/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type UpdateLoginProjectReq struct {
	LoginProtect *UpdateLoginProject `json:"login_protect"`
}

func (o UpdateLoginProjectReq) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateLoginProjectReq", string(data)}, " ")
}
