/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type PwdAuth struct {
	Identity *PwdIdentity `json:"identity"`
	Scope    *AuthScope   `json:"scope"`
}

func (o PwdAuth) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"PwdAuth", string(data)}, " ")
}
