/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type Region struct {
	// 区域描述信息。
	Description string `json:"description"`
	// null.
	ParentRegionId string `json:"parent_region_id"`
	Links *LinksSelf `json:"links"`
	Locales *RegionLocales `json:"locales"`
	// 区域ID。
	Id string `json:"id"`
	// 区域类型。
	Type string `json:"type"`
}
