/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneCheckroleForGroupRequest struct {
	DomainId string `json:"domain_id"`
	GroupId  string `json:"group_id"`
	RoleId   string `json:"role_id"`
}

func (o KeystoneCheckroleForGroupRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneCheckroleForGroupRequest", string(data)}, " ")
}
