/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneListServicesRequest struct {
	Type string `json:"type,omitempty"`
}

func (o KeystoneListServicesRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListServicesRequest", string(data)}, " ")
}
