/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type CreateTemporaryAccessKeyByAgencyRequestBody struct {
	Auth *AgencyAuth `json:"auth"`
}
