/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type LoginTokenAuth struct {
	Securitytoken *LoginTokenSecurityToken `json:"securitytoken"`
}

func (o LoginTokenAuth) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"LoginTokenAuth", string(data)}, " ")
}
