/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type LoginTokenAssumedBy struct {
	User *LoginTokenUser `json:"user,omitempty"`
}

func (o LoginTokenAssumedBy) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"LoginTokenAssumedBy", string(data)}, " ")
}
