/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateUnscopeTokenByIdpInitiatedResponse struct {
	Token          *IdpToken `json:"token,omitempty"`
	XSubjectToken  *string   `json:"X-Subject-Token,omitempty"`
	HttpStatusCode int       `json:"-"`
}

func (o CreateUnscopeTokenByIdpInitiatedResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateUnscopeTokenByIdpInitiatedResponse", string(data)}, " ")
}
