/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

//
type TokenAuth struct {
	Identity *TokenAuthIdentity `json:"identity"`
}

func (o TokenAuth) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"TokenAuth", string(data)}, " ")
}
