/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateDomainPasswordPolicyResponse struct {
	PasswordPolicy *PasswordPolicyResult `json:"password_policy,omitempty"`
}

func (o UpdateDomainPasswordPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateDomainPasswordPolicyResponse", string(data)}, " ")
}
