/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneShowEndpointRequest struct {
	EndpointId string `json:"endpoint_id"`
}
