/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneShowServiceRequest struct {
	ServiceId string `json:"service_id"`
}

func (o KeystoneShowServiceRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowServiceRequest", string(data)}, " ")
}
