/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type VersionMediatypes struct {
	// 媒体类型。
	Type string `json:"type"`
	// 基础类型。
	Base string `json:"base"`
}
