/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type KeystoneShowProjectRequest struct {
	ProjectId string `json:"project_id"`
}

func (o KeystoneShowProjectRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneShowProjectRequest", string(data)}, " ")
}
