/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type KeystoneUpdateGroupRequestBody struct {
	Group *KeystoneUpdateGroupOption `json:"group"`
}

func (o KeystoneUpdateGroupRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneUpdateGroupRequestBody", string(data)}, " ")
}
