/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowMetadataRequest struct {
	IdpId      string `json:"idp_id"`
	ProtocolId string `json:"protocol_id"`
}

func (o ShowMetadataRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowMetadataRequest", string(data)}, " ")
}
