/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type AgencyAuthIdentity struct {
	// 认证方法，该字段内容为[\"assume_role\"]。
	Methods []string `json:"methods"`
	AssumeRole *IdentityAssumerole `json:"assume_role"`
	Policy *ServicePolicy `json:"policy,omitempty"`
}
