/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneDeleteMappingRequest struct {
	Id string `json:"id"`
}

func (o KeystoneDeleteMappingRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneDeleteMappingRequest", string(data)}, " ")
}
