/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneUpdateProjectRequest struct {
	ProjectId string `json:"project_id"`
	Body *KeystoneUpdateProjectRequestBody `json:"body,omitempty"`
}
