/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CreateAgencyCustomPolicyRequest struct {
	Body *CreateAgencyCustomPolicyRequestBody `json:"body,omitempty"`
}
