/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type TokenAuthIdentity struct {
	// 认证方法，该字段内容为[\"token\"]。
	Methods []string `json:"methods"`
	Token *IdentityToken `json:"token,omitempty"`
	Policy *ServicePolicy `json:"policy,omitempty"`
}
