/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type AgencyTokenScope struct {
	Domain  *AgencyTokenScopeDomain  `json:"domain,omitempty"`
	Project *AgencyTokenScopeProject `json:"project,omitempty"`
}

func (o AgencyTokenScope) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"AgencyTokenScope", string(data)}, " ")
}
