/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type CreateAgencyCustomPolicyRequest struct {
	Body *CreateAgencyCustomPolicyRequestBody `json:"body,omitempty"`
}

func (o CreateAgencyCustomPolicyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateAgencyCustomPolicyRequest", string(data)}, " ")
}
