/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

//
type UpdateProjectOption struct {
	// 项目的状态信息，参数的值为\"suspended\"或\"normal\"。   - status值为\"suspended\"时，会将项目设置为冻结状态。   - status值为\"normal\"时，会将项目设置为正常（解冻）状态。
	Status UpdateProjectOptionStatus `json:"status"`
}

func (o UpdateProjectOption) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateProjectOption", string(data)}, " ")
}

type UpdateProjectOptionStatus struct {
	value string
}

type UpdateProjectOptionStatusEnum struct {
	SUSPENDED UpdateProjectOptionStatus
	NORMAL    UpdateProjectOptionStatus
}

func GetUpdateProjectOptionStatusEnum() UpdateProjectOptionStatusEnum {
	return UpdateProjectOptionStatusEnum{
		SUSPENDED: UpdateProjectOptionStatus{
			value: "suspended",
		},
		NORMAL: UpdateProjectOptionStatus{
			value: "normal",
		},
	}
}

func (c UpdateProjectOptionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *UpdateProjectOptionStatus) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
