/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type UpdatePermanentAccessKeyRequest struct {
	AccessKey string `json:"access_key"`
	Body *UpdatePermanentAccessKeyRequestBody `json:"body,omitempty"`
}
