/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type SecurityCompliance struct {
	// 密码强度策略的正则表达式。
	PasswordRegex string `json:"password_regex"`
	// 密码强度策略的描述。
	PasswordRegexDescription string `json:"password_regex_description"`
}
