/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListPermanentAccessKeysResponse struct {
	// 认证结果信息列表。
	Credentials    *[]Credentials `json:"credentials,omitempty"`
	HttpStatusCode int            `json:"-"`
}

func (o ListPermanentAccessKeysResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListPermanentAccessKeysResponse", string(data)}, " ")
}
