/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneListEndpointsRequest struct {
	Interface string `json:"interface,omitempty"`
	ServiceId string `json:"service_id,omitempty"`
}
