/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type UpdateUserResponse struct {
	User *UpdateUserResult `json:"user,omitempty"`
}
