/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type KeystoneListProjectsForUserRequest struct {
	UserId string `json:"user_id"`
}
