/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateUserResponse struct {
	User *CreateUserResult `json:"user,omitempty"`
}

func (o CreateUserResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateUserResponse", string(data)}, " ")
}
