/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateDomainApiAclPolicyResponse struct {
	ApiAclPolicy *AclPolicyResult `json:"api_acl_policy,omitempty"`
}

func (o UpdateDomainApiAclPolicyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateDomainApiAclPolicyResponse", string(data)}, " ")
}
