/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type OsfederationIdentityprovider struct {
	// 身份提供商ID。
	Id string `json:"id"`
}

func (o OsfederationIdentityprovider) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"OsfederationIdentityprovider", string(data)}, " ")
}
