/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListPermanentAccessKeysResponse struct {
	// 认证结果信息列表。
	Credentials []Credentials `json:"credentials,omitempty"`
}
