/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type PolicyDepends struct {
	// 权限所在目录。
	Catalog string `json:"catalog"`
	// 权限展示名。
	DisplayName string `json:"display_name"`
}
