/*
 * IAM
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type KeystoneListUsersRequest struct {
	Enabled           *bool   `json:"enabled,omitempty"`
	Name              *string `json:"name,omitempty"`
	PasswordExpiresAt *string `json:"password_expires_at,omitempty"`
}

func (o KeystoneListUsersRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"KeystoneListUsersRequest", string(data)}, " ")
}
