/*
    * IAM
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListDomainPermissionsForAgencyRequest struct {
	AgencyId string `json:"agency_id"`
}
