/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// This is a auto create Body Object
type CinderExportToImageRequestBody struct {
	OsVolumeUploadImage *CinderExportToImageOption `json:"os-volume_upload_image"`
}
