/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type RollbackSnapshotRequest struct {
	SnapshotId string `json:"snapshot_id"`
	Body *RollbackSnapshotRequestBody `json:"body,omitempty"`
}
