/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 一个az对象
type AzInfo struct {
	// 可用分区的名字。
	ZoneName string `json:"zoneName"`
	ZoneState *ZoneState `json:"zoneState"`
}
