/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CinderExportToImageRequest struct {
	VolumeId string `json:"volume_id"`
	Body *CinderExportToImageRequestBody `json:"body,omitempty"`
}
