/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ShowVolumeResponse struct {
	Volume *VolumeDetail `json:"volume,omitempty"`
}
