/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type DeleteSnapshotRequest struct {
	SnapshotId string `json:"snapshot_id"`
}
