/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type CinderListAvailabilityZonesResponse struct {
	// 查询请求返回的可用分区列表，请参见• [availabilityZoneInfo参数说明](https://support.huaweicloud.com/api-evs/evs_04_2081.html#evs_04_2081__li19751007201910)。
	AvailabilityZoneInfo []AzInfo `json:"availabilityZoneInfo,omitempty"`
}
