/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 可用分区的状态。
type ZoneState struct {
	// 可用分区是否可用。
	Available bool `json:"available,omitempty"`
}
