/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// This is a auto create Body Object
type BatchCreateVolumeTagsRequestBody struct {
	// 操作标识，当前支持的取值如下：  添加标签：create
	Action string `json:"action"`
	// 标签列表。
	Tags []Tag `json:"tags"`
}
