/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type Match struct {
	// 键。取值范围如下： resource_name：资源名称。 service_type：服务类型。
	Key string `json:"key"`
	// 值。最大长度255个字符。 key为“resource_name”时，value为模糊匹配。
	Value string `json:"value"`
}
