/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ShowVolumeTagsRequest struct {
	VolumeId string `json:"volume_id"`
}
