/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListVolumeTagsResponse struct {
	// 所有云硬盘的标签信息
	Tags map[string][]string `json:"tags,omitempty"`
}
