/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type RollbackSnapshotOption struct {
	// 回滚的目标云硬盘名称。
	Name string `json:"name,omitempty"`
	// 回滚的目标云硬盘UUID。
	VolumeId string `json:"volume_id"`
}
