/*
 * EVS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// This is a auto create Body Object
type BatchDeleteVolumeTagsRequestBody struct {
	// 操作标识，当前支持的取值如下：  删除标签：delete
	Action BatchDeleteVolumeTagsRequestBodyAction `json:"action"`
	// 标签列表。
	Tags []DeleteTagsOption `json:"tags"`
}

func (o BatchDeleteVolumeTagsRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"BatchDeleteVolumeTagsRequestBody", string(data)}, " ")
}

type BatchDeleteVolumeTagsRequestBodyAction struct {
	value string
}

type BatchDeleteVolumeTagsRequestBodyActionEnum struct {
	DELETE BatchDeleteVolumeTagsRequestBodyAction
}

func GetBatchDeleteVolumeTagsRequestBodyActionEnum() BatchDeleteVolumeTagsRequestBodyActionEnum {
	return BatchDeleteVolumeTagsRequestBodyActionEnum{
		DELETE: BatchDeleteVolumeTagsRequestBodyAction{
			value: "delete",
		},
	}
}

func (c BatchDeleteVolumeTagsRequestBodyAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *BatchDeleteVolumeTagsRequestBodyAction) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
