/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type RollbackInfo struct {
	// 回滚的目标云硬盘UUID。
	VolumeId string `json:"volume_id"`
}
