/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CinderListQuotasRequest struct {
	TargetProjectId string `json:"target_project_id"`
	Usage string `json:"usage"`
}
