/*
    * EVS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// This is a auto create Body Object
type ResizeVolumeRequestBody struct {
	BssParam *BssParamForResizeVolume `json:"bssParam,omitempty"`
	OsExtend *OsExtend `json:"os-extend"`
}
