/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowL7ruleResponse struct {
	Rule *L7ruleV2Resp `json:"rule,omitempty"`
}

func (o ShowL7ruleResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowL7ruleResponse", string(data)}, " ")
}
