/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 负载均衡器状态树对象
type StatusResp struct {
	Loadbalancer *LoadbalancerInStatusResp `json:"loadbalancer"`
}

func (o StatusResp) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"StatusResp", string(data)}, " ")
}
