/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DeleteMemberRequest struct {
	PoolId   string `json:"pool_id"`
	MemberId string `json:"member_id"`
}

func (o DeleteMemberRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteMemberRequest", string(data)}, " ")
}
