/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListL7rulesResponse struct {
	// 转发规则对象的列表
	Rules *[]L7ruleResp `json:"rules,omitempty"`
}

func (o ListL7rulesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListL7rulesResponse", string(data)}, " ")
}
