/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListMenbersResponse struct {
	// 后端云服务器对象的列表
	Members *[]MemberResp `json:"members,omitempty"`
}

func (o ListMenbersResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListMenbersResponse", string(data)}, " ")
}
