/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateHealthmonitorRequest struct {
	Body *CreateHealthmonitorRequestBody `json:"body,omitempty"`
}

func (o CreateHealthmonitorRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateHealthmonitorRequest", string(data)}, " ")
}
