/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateLoadbalancerResponse struct {
	Loadbalancer *LoadbalancerV2Resp `json:"loadbalancer,omitempty"`
}

func (o CreateLoadbalancerResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateLoadbalancerResponse", string(data)}, " ")
}
