/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// This is a auto create Body Object
type UpdateHealthmonitorRequestBody struct {
	Healthmonitor *UpdateHealthmonitorV2Req `json:"healthmonitor"`
}

func (o UpdateHealthmonitorRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateHealthmonitorRequestBody", string(data)}, " ")
}
