/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// This is a auto create Body Object
type CreateL7policyRequestBody struct {
	L7policy *CreateL7policyReq `json:"l7policy"`
}

func (o CreateL7policyRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateL7policyRequestBody", string(data)}, " ")
}
