/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateL7policyResponse struct {
	L7policy       *L7policyResp `json:"l7policy,omitempty"`
	HttpStatusCode int           `json:"-"`
}

func (o CreateL7policyResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateL7policyResponse", string(data)}, " ")
}
