/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateL7policyRequest struct {
	Body *CreateL7policyRequestBody `json:"body,omitempty"`
}

func (o CreateL7policyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateL7policyRequest", string(data)}, " ")
}
