/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 更新负载均衡器的请求体
type UpdateLoadbalancerV2Req struct {
	// 负载均衡器名称。
	Name *string `json:"name,omitempty"`
	// 负载均衡器的描述信息
	Description *string `json:"description,omitempty"`
	// 负载均衡器的管理状态。只支持设定为true，该字段的值无实际意义。
	AdminStateUp *bool `json:"admin_state_up,omitempty"`
}

func (o UpdateLoadbalancerV2Req) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateLoadbalancerV2Req", string(data)}, " ")
}
