/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateListenerResponse struct {
	Listener *ListenerV2Resp `json:"listener,omitempty"`
}

func (o UpdateListenerResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateListenerResponse", string(data)}, " ")
}
