/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowMemberResponse struct {
	Member *MemberResp `json:"member,omitempty"`
}

func (o ShowMemberResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowMemberResponse", string(data)}, " ")
}
