/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 监听器对象列表，用于状态树中
type ListenersV2InStatusResp struct {
	// 监听器ID
	Id string `json:"id"`
	// 监听器名称
	Name string `json:"name"`
	// 监听器关联的后端云服务器组列表
	Pools []PoolsV2InStatusResp `json:"pools"`
	// 监听器关联的转发策略列表
	L7policies []L7policiesV2InStatusResp `json:"l7policies"`
	// 监听器的操作状态；该字段为预留字段，暂未启用。默认为ONLINE。
	OperatingStatus string `json:"operating_status"`
	// 监听器的配置状态；该字段为预留字段，暂未启用。默认为ACTIVE。
	ProvisioningStatus string `json:"provisioning_status"`
}

func (o ListenersV2InStatusResp) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListenersV2InStatusResp", string(data)}, " ")
}
