/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateListenerResponse struct {
	Listener       *ListenerResp `json:"listener,omitempty"`
	HttpStatusCode int           `json:"-"`
}

func (o CreateListenerResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateListenerResponse", string(data)}, " ")
}
