/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListLoadbalancersResponse struct {
	// 负载均衡器对象列表
	Loadbalancers *[]LoadbalancerV2Resp `json:"loadbalancers,omitempty"`
}

func (o ListLoadbalancersResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListLoadbalancersResponse", string(data)}, " ")
}
