/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListL7policiesResponse struct {
	// 转发策略对象的列表
	L7policies *[]L7policyV2Resp `json:"l7policies,omitempty"`
}

func (o ListL7policiesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListL7policiesResponse", string(data)}, " ")
}
