/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateL7ruleRequest struct {
	L7policyId string                   `json:"l7policy_id"`
	Body       *CreateL7ruleRequestBody `json:"body,omitempty"`
}

func (o CreateL7ruleRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateL7ruleRequest", string(data)}, " ")
}
