/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ShowWhitelistResponse struct {
	Whitelist      *WhitelistResp `json:"whitelist,omitempty"`
	HttpStatusCode int            `json:"-"`
}

func (o ShowWhitelistResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowWhitelistResponse", string(data)}, " ")
}
