/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowWhitelistRequest struct {
	WhitelistId string `json:"whitelist_id"`
}

func (o ShowWhitelistRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowWhitelistRequest", string(data)}, " ")
}
