/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// This is a auto create Body Object
type UpdateL7ruleRequestBody struct {
	Rule *UpdateL7ruleV2Req `json:"rule"`
}

func (o UpdateL7ruleRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateL7ruleRequestBody", string(data)}, " ")
}
