/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateL7policiesResponse struct {
	L7policy *L7policyV2Resp `json:"l7policy,omitempty"`
}

func (o UpdateL7policiesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateL7policiesResponse", string(data)}, " ")
}
