/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListListenersResponse struct {
	// 监听器对象列表
	Listeners *[]ListenerV2Resp `json:"listeners,omitempty"`
}

func (o ListListenersResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListListenersResponse", string(data)}, " ")
}
