/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// This is a auto create Body Object
type UpdateWhitelistRequestBody struct {
	Whitelist *UpdateWhitelistV2Req `json:"whitelist"`
}

func (o UpdateWhitelistRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateWhitelistRequestBody", string(data)}, " ")
}
