/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// This is a auto create Body Object
type UpdateL7policiesRequestBody struct {
	L7policy *UpdateL7policyV2Req `json:"l7policy"`
}

func (o UpdateL7policiesRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateL7policiesRequestBody", string(data)}, " ")
}
