/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type UpdateLoadbalancerRequest struct {
	LoadbalancerId string                         `json:"loadbalancer_id"`
	Body           *UpdateLoadbalancerRequestBody `json:"body,omitempty"`
}

func (o UpdateLoadbalancerRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateLoadbalancerRequest", string(data)}, " ")
}
