/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowL7policyRequest struct {
	L7policyId string `json:"l7policy_id"`
}

func (o ShowL7policyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowL7policyRequest", string(data)}, " ")
}
