/*
 * ELB
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateLoadbalancerResponse struct {
	Loadbalancer   *LoadbalancerResp `json:"loadbalancer,omitempty"`
	HttpStatusCode int               `json:"-"`
}

func (o UpdateLoadbalancerResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateLoadbalancerResponse", string(data)}, " ")
}
