/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateCheckpointResponse struct {
	Checkpoint     *CheckpointCreate `json:"checkpoint,omitempty"`
	HttpStatusCode int               `json:"-"`
}

func (o CreateCheckpointResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateCheckpointResponse", string(data)}, " ")
}
