/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type CheckpointPlanCreate struct {
	// 存储库id
	Id string `json:"id"`
	// 存储库名称
	Name string `json:"name"`
	// 备份对象
	Resources []Resource `json:"resources,omitempty"`
	// 备份时跳过的资源列表
	SkippedResources []CheckpointCreateSkippedResource `json:"skipped_resources,omitempty"`
}
