/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type PolicyTriggerReq struct {
	Properties *PolicyTriggerPropertiesReq `json:"properties"`
}
