/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListVaultRequest struct {
	Limit int32 `json:"limit,omitempty"`
	Name string `json:"name,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	CloudType string `json:"cloud_type,omitempty"`
	ProtectType string `json:"protect_type,omitempty"`
	ObjectType string `json:"object_type,omitempty"`
	EnterpriseProjectId string `json:"enterprise_project_id,omitempty"`
	Id string `json:"id,omitempty"`
	PolicyId string `json:"policy_id,omitempty"`
	Status string `json:"status,omitempty"`
	ResourceIds string `json:"resource_ids,omitempty"`
}
