/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type AddVaultResourceResponse struct {
	// 已添加的资源ID列表
	AddResourceIds []string `json:"add_resource_ids,omitempty"`
}
