/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

type PolicyCreateReq struct {
	Policy *PolicyCreate `json:"policy"`
}

func (o PolicyCreateReq) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"PolicyCreateReq", string(data)}, " ")
}
