/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListPoliciesRequest struct {
	OperationType string `json:"operation_type,omitempty"`
	VaultId string `json:"vault_id,omitempty"`
}
