/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type ImportBackupRequest struct {
	Body *BackupSyncReq `json:"body,omitempty"`
}

func (o ImportBackupRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ImportBackupRequest", string(data)}, " ")
}
