/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

type Vault struct {
	Billing *Billing `json:"billing"`
	// 存储库自定义描述信息。
	Description string `json:"description,omitempty"`
	// 保管库ID
	Id string `json:"id"`
	// 保管库名称
	Name string `json:"name"`
	// 项目ID
	ProjectId string `json:"project_id"`
	// 保管库类型
	ProviderId string `json:"provider_id"`
	// 存储库资源
	Resources []ResourceResp `json:"resources"`
	// 存储库标签
	Tags []Tag `json:"tags,omitempty"`
	// 企业项目id，默认为‘0’。
	EnterpriseProjectId string `json:"enterprise_project_id,omitempty"`
	// 是否自动绑定，默认为false，不支持。
	AutoBind string `json:"auto_bind,omitempty"`
	// 绑定规则
	BindRules string `json:"bind_rules,omitempty"`
	// 用户id
	UserId string `json:"user_id,omitempty"`
	// 创建时间
	CreatedAt string `json:"created_at,omitempty"`
}

func (o Vault) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"Vault", string(data)}, " ")
}
