/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

type BillingUpdate struct {
	// 存储库规格
	ConsistentLevel BillingUpdateConsistentLevel `json:"consistent_level,omitempty"`
	// 存储库大小，单位为GB
	Size *int32 `json:"size,omitempty"`
}

func (o BillingUpdate) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"BillingUpdate", string(data)}, " ")
}

type BillingUpdateConsistentLevel struct {
	value string
}

type BillingUpdateConsistentLevelEnum struct {
	APP_CONSISTENT   BillingUpdateConsistentLevel
	CRASH_CONSISTENT BillingUpdateConsistentLevel
}

func GetBillingUpdateConsistentLevelEnum() BillingUpdateConsistentLevelEnum {
	return BillingUpdateConsistentLevelEnum{
		APP_CONSISTENT: BillingUpdateConsistentLevel{
			value: "app_consistent",
		},
		CRASH_CONSISTENT: BillingUpdateConsistentLevel{
			value: "crash_consistent",
		},
	}
}

func (c BillingUpdateConsistentLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *BillingUpdateConsistentLevel) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
