/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListBackupsResponse struct {
	// 备份列表
	Backups []BackupResp `json:"backups,omitempty"`
	// 备份个数
	Count int32 `json:"count,omitempty"`
}
