/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 
type ResourceExtraInfoIncludeVolumes struct {
	// 卷ID，仅支持uuid
	Id string `json:"id"`
	// 操作系统类型
	OsVersion string `json:"os_version,omitempty"`
}
