/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type UpdatePolicyRequest struct {
	PolicyId string           `json:"policy_id"`
	Body     *PolicyUpdateReq `json:"body,omitempty"`
}

func (o UpdatePolicyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdatePolicyRequest", string(data)}, " ")
}
