/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type ListProtectableRequest struct {
	Limit           int32                                 `json:"limit,omitempty"`
	Marker          string                                `json:"marker,omitempty"`
	Name            string                                `json:"name,omitempty"`
	Offset          int32                                 `json:"offset,omitempty"`
	ProtectableType ListProtectableRequestProtectableType `json:"protectable_type"`
	Status          string                                `json:"status,omitempty"`
	Id              string                                `json:"id,omitempty"`
	ServerId        string                                `json:"server_id,omitempty"`
}

func (o ListProtectableRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListProtectableRequest", string(data)}, " ")
}

type ListProtectableRequestProtectableType struct {
	value string
}

type ListProtectableRequestProtectableTypeEnum struct {
	SERVER ListProtectableRequestProtectableType
	DISK   ListProtectableRequestProtectableType
}

func GetListProtectableRequestProtectableTypeEnum() ListProtectableRequestProtectableTypeEnum {
	return ListProtectableRequestProtectableTypeEnum{
		SERVER: ListProtectableRequestProtectableType{
			value: "server",
		},
		DISK: ListProtectableRequestProtectableType{
			value: "disk",
		},
	}
}

func (c ListProtectableRequestProtectableType) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *ListProtectableRequestProtectableType) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
