/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 执行复制请求体
type CheckpointReplicateReq struct {
	Replicate *CheckpointReplicateParam `json:"replicate"`
}
