/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 策略修改body
type PolicyUpdateReq struct {
	Policy *PolicyUpdate `json:"policy"`
}
