/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ShowOpLogResponse struct {
	OperationLog *OperationLog `json:"operation_log,omitempty"`
}
