/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type RestoreBackupResponse struct {
}

func (o RestoreBackupResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"RestoreBackupResponse", string(data)}, " ")
}
