/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ShowCheckpointRequest struct {
	CheckpointId string `json:"checkpoint_id"`
}
