/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type CheckpointReplicateRespbackups struct {
	// 待复制的备份ID
	BackupId string `json:"backup_id"`
	// 复制记录ID
	ReplicationRecordId string `json:"replication_record_id"`
}
