/*
 * CBR
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type AddVaultResourceRequest struct {
	VaultId string               `json:"vault_id"`
	Body    *VaultAddResourceReq `json:"body,omitempty"`
}

func (o AddVaultResourceRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"AddVaultResourceRequest", string(data)}, " ")
}
