/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type ShowBackupResponse struct {
	Backup *BackupDetail `json:"backup,omitempty"`
}

func (o ShowBackupResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowBackupResponse", string(data)}, " ")
}
