/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type ProtectableReplicationCapabilitiesRespRegion struct {
	// 云服务所在的区域
	Name string `json:"name"`
	// 支持复制的目标区域列表
	ReplicationDestinations []string `json:"replication_destinations"`
}
