/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type VaultBackup struct {
	Parameters *CheckpointParam `json:"parameters,omitempty"`
	// 存储库ID
	VaultId string `json:"vault_id"`
}
