/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type RemoveVaultResourceResponse struct {
	// 移除的资源ID
	RemoveResourceIds []string `json:"remove_resource_ids,omitempty"`
}
