/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ShowOpLogRequest struct {
	OperationLogId string `json:"operation_log_id"`
}
