/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type VaultUpdate struct {
	Billing *BillingUpdate `json:"billing,omitempty"`
	// 存储库名称
	Name string `json:"name,omitempty"`
	// 是否支持自动挂载
	AutoBind bool `json:"auto_bind,omitempty"`
	// 
	BindRules []VaultBindRules `json:"bind_rules,omitempty"`
}
