/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowVaultResourceInstancesRequest struct {
	Body *VaultResourceInstancesReq `json:"body,omitempty"`
}

func (o ShowVaultResourceInstancesRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowVaultResourceInstancesRequest", string(data)}, " ")
}
