/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CopyBackupRequest struct {
	BackupId string `json:"backup_id"`
	Body *BackupReplicateReq `json:"body,omitempty"`
}
