/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type VaultAddResourceReq struct {
	// 资源列表
	Resources []ResourceCreate `json:"resources"`
}
