/*
 * CBR
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

type PolicyTriggerReq struct {
	Properties *PolicyTriggerPropertiesReq `json:"properties"`
}

func (o PolicyTriggerReq) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"PolicyTriggerReq", string(data)}, " ")
}
