/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type CreateCheckpointResponse struct {
	Checkpoint *CheckpointCreate `json:"checkpoint,omitempty"`
}
