/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type CheckpointCreate struct {
	// 创建时间，例如:\"2020-02-05T10:38:34.209782\"
	CreatedAt string `json:"created_at"`
	// 还原点ID
	Id string `json:"id"`
	// 项目ID
	ProjectId string `json:"project_id"`
	// 状态
	Status string `json:"status"`
	Vault *CheckpointPlanCreate `json:"vault,omitempty"`
	ExtraInfo *BackupExtendInfo `json:"extra_info,omitempty"`
}
