/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowMemberDetailRequest struct {
	BackupId string `json:"backup_id"`
	MemberId string `json:"member_id"`
}

func (o ShowMemberDetailRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowMemberDetailRequest", string(data)}, " ")
}
