/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ShowMembersDetailRequest struct {
	BackupId string `json:"backup_id"`
	DestProjectId string `json:"dest_project_id,omitempty"`
	ImageId string `json:"image_id,omitempty"`
	Status string `json:"status,omitempty"`
	VaultId string `json:"vault_id,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Marker string `json:"marker,omitempty"`
	Offset int32 `json:"offset,omitempty"`
	Sort string `json:"sort,omitempty"`
}
