/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListPoliciesResponse struct {
	// 
	Policies []Policy `json:"policies,omitempty"`
}
