/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type OpExtendInfoDelete struct {
	// 备份副本ID
	BackupId string `json:"backup_id"`
	// 备份名称
	BackupName string `json:"backup_name"`
}
