/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type BackupSyncReq struct {
	// 待同步备份副本列表
	Sync []BackupSync `json:"sync"`
}
