/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type UpdatePolicyRequest struct {
	PolicyId string `json:"policy_id"`
	Body *PolicyUpdateReq `json:"body,omitempty"`
}
