/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateMemberStatusResponse struct {
	Member         *Member `json:"member,omitempty"`
	HttpStatusCode int     `json:"-"`
}

func (o UpdateMemberStatusResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateMemberStatusResponse", string(data)}, " ")
}
