/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type AddMemberResponse struct {
	// 添加备份共享成员响应信息
	Members []Member `json:"members,omitempty"`
}
