/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type ListVaultRequest struct {
	Limit               int32                       `json:"limit,omitempty"`
	Name                string                      `json:"name,omitempty"`
	Offset              int32                       `json:"offset,omitempty"`
	CloudType           ListVaultRequestCloudType   `json:"cloud_type,omitempty"`
	ProtectType         ListVaultRequestProtectType `json:"protect_type,omitempty"`
	ObjectType          string                      `json:"object_type,omitempty"`
	EnterpriseProjectId string                      `json:"enterprise_project_id,omitempty"`
	Id                  string                      `json:"id,omitempty"`
	PolicyId            string                      `json:"policy_id,omitempty"`
	Status              string                      `json:"status,omitempty"`
	ResourceIds         string                      `json:"resource_ids,omitempty"`
}

func (o ListVaultRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListVaultRequest", string(data)}, " ")
}

type ListVaultRequestCloudType struct {
	value string
}

type ListVaultRequestCloudTypeEnum struct {
	PUBLIC ListVaultRequestCloudType
	HYBRID ListVaultRequestCloudType
}

func GetListVaultRequestCloudTypeEnum() ListVaultRequestCloudTypeEnum {
	return ListVaultRequestCloudTypeEnum{
		PUBLIC: ListVaultRequestCloudType{
			value: "public",
		},
		HYBRID: ListVaultRequestCloudType{
			value: "hybrid",
		},
	}
}

func (c ListVaultRequestCloudType) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *ListVaultRequestCloudType) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}

type ListVaultRequestProtectType struct {
	value string
}

type ListVaultRequestProtectTypeEnum struct {
	BACKUP      ListVaultRequestProtectType
	REPLICATION ListVaultRequestProtectType
}

func GetListVaultRequestProtectTypeEnum() ListVaultRequestProtectTypeEnum {
	return ListVaultRequestProtectTypeEnum{
		BACKUP: ListVaultRequestProtectType{
			value: "backup",
		},
		REPLICATION: ListVaultRequestProtectType{
			value: "replication",
		},
	}
}

func (c ListVaultRequestProtectType) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *ListVaultRequestProtectType) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
