/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

type Policy struct {
	// 策略是否启用
	Enabled bool `json:"enabled"`
	// 策略ID
	Id string `json:"id"`
	// 策略名称
	Name                string           `json:"name"`
	OperationDefinition *PolicyoOdCreate `json:"operation_definition"`
	// 策略类型,例如 ‘backup’：自动备份
	OperationType PolicyOperationType `json:"operation_type"`
	Trigger       *PolicyTriggerResp  `json:"trigger"`
	// 关联的存储库
	AssociatedVaults []PolicyAssociateVault `json:"associated_vaults,omitempty"`
}

func (o Policy) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"Policy", string(data)}, " ")
}

type PolicyOperationType struct {
	value string
}

type PolicyOperationTypeEnum struct {
	BACKUP      PolicyOperationType
	REPLICATION PolicyOperationType
}

func GetPolicyOperationTypeEnum() PolicyOperationTypeEnum {
	return PolicyOperationTypeEnum{
		BACKUP: PolicyOperationType{
			value: "backup",
		},
		REPLICATION: PolicyOperationType{
			value: "replication",
		},
	}
}

func (c PolicyOperationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *PolicyOperationType) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
