/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DisassociateVaultPolicyRequest struct {
	VaultId string           `json:"vault_id"`
	Body    *VaultDissociate `json:"body,omitempty"`
}

func (o DisassociateVaultPolicyRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DisassociateVaultPolicyRequest", string(data)}, " ")
}
