/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type ResourceResp struct {
	ExtraInfo *ResourceExtraInfo `json:"extra_info,omitempty"`
	// 待备份资源id
	Id string `json:"id"`
	// 待备份资源名称
	Name string `json:"name"`
	// 保护状态
	ProtectStatus string `json:"protect_status,omitempty"`
	// 资源已分配容量,单位为GB
	Size int32 `json:"size,omitempty"`
	// [待备份资源的类型: OS::Nova::Server, OS::Cinder::Volume, OS::Ironic::BareMetalServer, OS::Native::Server, OS::Sfs::Turbo](tag:hws,hws_hk,fcs_vm,ctc) [待备份资源的类型: OS::Nova::Server,  OS::Cinder::Volume](tag:dt,ocb,tlf,sbc)
	Type string `json:"type"`
	// 副本大小
	BackupSize string `json:"backup_size,omitempty"`
	// 副本数量
	BackupCount string `json:"backup_count,omitempty"`
}
