/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type DeletePolicyRequest struct {
	PolicyId string `json:"policy_id"`
}
