/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ImportBackupRequest struct {
	Body *BackupSyncReq `json:"body,omitempty"`
}
