/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DeleteVaultRequest struct {
	VaultId string `json:"vault_id"`
}

func (o DeleteVaultRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteVaultRequest", string(data)}, " ")
}
