/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type RemoveVaultResourceResponse struct {
	// 移除的资源ID
	RemoveResourceIds *[]string `json:"remove_resource_ids,omitempty"`
}

func (o RemoveVaultResourceResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"RemoveVaultResourceResponse", string(data)}, " ")
}
