/*
 * CBR
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type MigrateVaultResourceResponse struct {
	//
	MigratedResources *[]string `json:"migrated_resources,omitempty"`
	HttpStatusCode    int       `json:"-"`
}

func (o MigrateVaultResourceResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"MigrateVaultResourceResponse", string(data)}, " ")
}
