/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type BillingUpdate struct {
	// 存储库规格
	ConsistentLevel string `json:"consistent_level,omitempty"`
	// 存储库大小，单位为GB
	Size int32 `json:"size,omitempty"`
}
