/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ShowReplicationCapabilitiesResponse struct {
	// 支持复制的区域列表
	Regions []ProtectableReplicationCapabilitiesRespRegion `json:"regions,omitempty"`
}
