/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ImportBackupResponse struct {
	// 同步备份副本接口的返回信息
	Sync []BackupSyncRespBody `json:"sync,omitempty"`
}
