/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

type VaultBindRules struct {
	// 字段key
	Key string `json:"key"`
	// 字段的值
	Value *string `json:"value,omitempty"`
}

func (o VaultBindRules) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"VaultBindRules", string(data)}, " ")
}
