/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type VaultDissociate struct {
	// 策略ID
	PolicyId string `json:"policy_id"`
}
