/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type VaultRemoveResourceReq struct {
	// 要移除的资源ID列表
	ResourceIds []string `json:"resource_ids"`
}
