/*
 * Cbr
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

type VaultCreateReq struct {
	Vault *VaultCreate `json:"vault"`
}

func (o VaultCreateReq) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"VaultCreateReq", string(data)}, " ")
}
