/*
    * Cbr
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CreateCheckpointRequest struct {
	Body *VaultBackupReq `json:"body,omitempty"`
}
