/*
 * EPS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateEnterpriseProjectResponse struct {
	EnterpriseProject *EpDetail `json:"enterprise_project,omitempty"`
}

func (o CreateEnterpriseProjectResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateEnterpriseProjectResponse", string(data)}, " ")
}
