/*
 * EPS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type MigrateResourceResponse struct {
}

func (o MigrateResourceResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"MigrateResourceResponse", string(data)}, " ")
}
