/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 配额信息
type QuotasDetail struct {
	// 资源配额
	Resources []EpQuotas `json:"resources"`
}
