/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListEpRequest struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Status int32 `json:"status,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Offset int32 `json:"offset"`
	SortKey string `json:"sort_key,omitempty"`
	SortDir string `json:"sort_dir,omitempty"`
}
