/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type CreateEpResponse struct {
	EnterpriseProject *EpDetail `json:"enterprise_project,omitempty"`
}
