/*
 * EPS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type EnableEnterpriseProjectResponse struct {
}

func (o EnableEnterpriseProjectResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"EnableEnterpriseProjectResponse", string(data)}, " ")
}
