/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// API的URL地址。
type Link struct {
	// API的URL地址。
	Href string `json:"href"`
	// self。
	Rel string `json:"rel"`
}
