/*
 * EPS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// 停用企业项目操作
type DisableAction struct {
	// 停用操作
	Action DisableActionAction `json:"action"`
}

func (o DisableAction) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DisableAction", string(data)}, " ")
}

type DisableActionAction struct {
	value string
}

type DisableActionActionEnum struct {
	DISABLE DisableActionAction
}

func GetDisableActionActionEnum() DisableActionActionEnum {
	return DisableActionActionEnum{
		DISABLE: DisableActionAction{
			value: "disable",
		},
	}
}

func (c DisableActionAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *DisableActionAction) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
