/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CreateEpRequest struct {
	Body *EnterpriseProject `json:"body,omitempty"`
}
