/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 停用启用企业项目操作
type EnableAction struct {
	// 启用操作
	Action string `json:"action"`
}
