/*
 * EPS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateEnterpriseProjectRequest struct {
	Body *EnterpriseProject `json:"body,omitempty"`
}

func (o CreateEnterpriseProjectRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateEnterpriseProjectRequest", string(data)}, " ")
}
