/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model
import (
	"github.com/huaweicloud/huaweicloud-sdk-go-v3/core/sdktime"
)

// 企业项目详情
type EpDetail struct {
	// 企业项目ID
	Id string `json:"id"`
	// 企业项目名称
	Name string `json:"name"`
	// 企业项目描述
	Description string `json:"description"`
	// 企业项目状态。1启用，2停用
	Status int32 `json:"status"`
	// 创建时间，格式为UTC格式。如：2018-05-18T06:49:06Z。
	CreatedAt *sdktime.SdkTime `json:"created_at"`
	// 修改时间，格式为UTC格式。如：2018-05-28T02:21:36Z。
	UpdatedAt *sdktime.SdkTime `json:"updated_at"`
}
