/*
    * EPS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListApiVersionsResponse struct {
	// 版本列表
	Versions []VersionDetail `json:"versions,omitempty"`
}
