/*
 * EPS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowEnterpriseProjectQuotaRequest struct {
}

func (o ShowEnterpriseProjectQuotaRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowEnterpriseProjectQuotaRequest", string(data)}, " ")
}
