/*
 * cts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type DeleteTrackerResponse struct {
}

func (o DeleteTrackerResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteTrackerResponse", string(data)}, " ")
}
