/*
    * cts
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 追踪桶信息。
type DataBucketQuery struct {
	// 标识OBS桶名称。由数字或字母开头，支持小写字母、数字、“-”、“.”，长度为3～63个字符。
	DataBucketName string `json:"data_bucket_name,omitempty"`
	// 追踪桶日志是否支持搜索。
	SearchEnabled bool `json:"search_enabled,omitempty"`
	// 追踪操作。
	DataEvent string `json:"data_event,omitempty"`
}
