/*
 * cts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListTracesResponse struct {
	// 本次查询事件列表返回事件数组。
	Traces   []Traces  `json:"traces,omitempty"`
	MetaData *MetaData `json:"meta_data,omitempty"`
}

func (o ListTracesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListTracesResponse", string(data)}, " ")
}
