/*
 * cts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

type DataBucket struct {
	// 数据类追踪器追踪对象的桶名。 - 当启用或者停用数据类追踪器时，该参数为必选。 - 管理类追踪器无此参数。 - 追踪器一旦创建追踪桶无法修改。
	DataBucketName string `json:"data_bucket_name,omitempty"`
	// 数据类追踪器追踪的操作类型。 - 当启用或者停用数据类追踪器时，该参数为必选。 - 管理类追踪器无此参数。
	DataEvent []DataBucketDataEvent `json:"data_event,omitempty"`
}

func (o DataBucket) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DataBucket", string(data)}, " ")
}

type DataBucketDataEvent struct {
	value string
}

type DataBucketDataEventEnum struct {
	WRITE DataBucketDataEvent
	READ  DataBucketDataEvent
}

func GetDataBucketDataEventEnum() DataBucketDataEventEnum {
	return DataBucketDataEventEnum{
		WRITE: DataBucketDataEvent{
			value: "WRITE",
		},
		READ: DataBucketDataEvent{
			value: "READ",
		},
	}
}

func (c DataBucketDataEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *DataBucketDataEvent) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
