/*
    * cts
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ListTracesResponse struct {
	// 本次查询事件列表返回事件数组。
	Traces []Traces `json:"traces,omitempty"`
	MetaData *MetaData `json:"meta_data,omitempty"`
}
