/*
 * cts
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type UpdateTrackerResponse struct {
}

func (o UpdateTrackerResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateTrackerResponse", string(data)}, " ")
}
