/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListAlarmHistoriesResponse struct {
	// 一条或者多条告警历史详细信息
	AlarmHistories *[]AlarmHistoryInfo      `json:"alarm_histories,omitempty"`
	MetaData       *MetaDataForAlarmHistory `json:"meta_data,omitempty"`
}

func (o ListAlarmHistoriesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListAlarmHistoriesResponse", string(data)}, " ")
}
