/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type UpdateResourceGroupRequest struct {
	ContentType string                          `json:"Content-Type"`
	GroupId     string                          `json:"group_id"`
	Body        *UpdateResourceGroupRequestBody `json:"body,omitempty"`
}

func (o UpdateResourceGroupRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateResourceGroupRequest", string(data)}, " ")
}
