/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type UpdateAlarmRequest struct {
	ContentType string                  `json:"Content-Type"`
	AlarmId     string                  `json:"alarm_id"`
	Body        *UpdateAlarmRequestBody `json:"body,omitempty"`
}

func (o UpdateAlarmRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateAlarmRequest", string(data)}, " ")
}
