/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateAlarmTemplateResponse struct {
	// 自定义告警模板创建成功返回的ID，如：at1603252280799wLRyGLxnz。
	TemplateId *string `json:"template_id,omitempty"`
}

func (o CreateAlarmTemplateResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateAlarmTemplateResponse", string(data)}, " ")
}
