/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type DatapointForBatchMetric struct {
	// 指标值，该字段名称与请求参数中filter使用的查询值相同；字段名称可为：max/min/average/sum/variance。
	Average float64 `json:"average"`
	// 指标采集时间，UNIX时间戳，单位毫秒。
	Timestamp int64 `json:"timestamp"`
}

func (o DatapointForBatchMetric) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DatapointForBatchMetric", string(data)}, " ")
}
