/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type BatchListMetricDataRequestBody struct {
	// 指标数据。数组长度最大10
	Metrics []MetricInfo `json:"metrics"`
	// 查询数据起始时间，UNIX时间戳，单位毫秒。建议from的值相对于当前时间向前偏移至少1个周期。由于聚合运算的过程是将一个聚合周期范围内的数据点聚合到周期起始边界上，如果将from和to的范围设置在聚合周期内，会因为聚合未完成而造成查询数据为空，所以建议from参数相对于当前时间向前偏移至少1个周期。以5分钟聚合周期为例：假设当前时间点为10:35，10:30~10:35之间的原始数据会被聚合到10:30这个点上，所以查询5分钟数据点时from参数应为10:30或之前。  说明： 云监控会根据所选择的聚合粒度向前取整from参数。
	From int64 `json:"from"`
	// 查询数据截止时间UNIX时间戳，单位毫秒。from必须小于to。
	To int64 `json:"to"`
	// 监控数据粒度。  取值范围：  \"1\"，原始数据 \"300\"，5分钟粒度 \"1200\"，20分钟粒度 \"3600\"，1小时粒度 \"14400\"，4小时粒度 \"86400\"，1天粒度
	Period string `json:"period"`
	// 数据聚合方式。  支持的值为max, min, average, sum, variance。  filter参数的值不会影响原始数据（period为1）的查询结果。
	Filter string `json:"filter"`
}

func (o BatchListMetricDataRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"BatchListMetricDataRequestBody", string(data)}, " ")
}
