/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

type AlarmActions struct {
	Type string `json:"type"`
	//
	NotificationList []string `json:"notificationList"`
}

func (o AlarmActions) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"AlarmActions", string(data)}, " ")
}
