/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreateAlarmResponse struct {
	//
	AlarmId *string `json:"alarm_id,omitempty"`
}

func (o CreateAlarmResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateAlarmResponse", string(data)}, " ")
}
