/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateEventsRequest struct {
	ContentType string      `json:"Content-Type"`
	Body        []EventItem `json:"body,omitempty"`
}

func (o CreateEventsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateEventsRequest", string(data)}, " ")
}
