/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListAlarmTemplatesRequest struct {
	ContentType     string  `json:"Content-Type"`
	AlarmTemplateId *string `json:"alarmTemplateId,omitempty"`
	Namespace       *string `json:"namespace,omitempty"`
	Dname           *string `json:"dname,omitempty"`
	Start           *string `json:"start,omitempty"`
	Limit           *string `json:"limit,omitempty"`
}

func (o ListAlarmTemplatesRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListAlarmTemplatesRequest", string(data)}, " ")
}
