/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DeleteAlarmTemplateRequest struct {
	ContentType string `json:"Content-Type"`
	TemplateId  string `json:"template_id"`
}

func (o DeleteAlarmTemplateRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteAlarmTemplateRequest", string(data)}, " ")
}
