/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

//
type Quotas struct {
	//
	Resources []Resource `json:"resources"`
}

func (o Quotas) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"Quotas", string(data)}, " ")
}
