/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

type Condition struct {
	ComparisonOperator string  `json:"comparison_operator"`
	Count              int32   `json:"count"`
	Filter             string  `json:"filter"`
	Period             int32   `json:"period"`
	Unit               *string `json:"unit,omitempty"`
	Value              int32   `json:"value"`
}

func (o Condition) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"Condition", string(data)}, " ")
}
