/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowAlarmRequest struct {
	ContentType string `json:"Content-Type"`
	AlarmId     string `json:"alarm_id"`
}

func (o ShowAlarmRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowAlarmRequest", string(data)}, " ")
}
