/*
 * CES
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListAlarmsResponse struct {
	// 告警对象列表。
	MetricAlarms *[]MetricAlarms `json:"metric_alarms,omitempty"`
	MetaData     *MetaData       `json:"meta_data,omitempty"`
}

func (o ListAlarmsResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListAlarmsResponse", string(data)}, " ")
}
