/*
 * CSBPartnerOpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ReclaimSubEnterpriseAmountResponse struct {
}

func (o ReclaimSubEnterpriseAmountResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ReclaimSubEnterpriseAmountResponse", string(data)}, " ")
}
