/*
 * Bss
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListCustomersBalancesDetailResponse struct {
	// |参数名称：总额，即最终优惠后的金额，| |参数约束以及描述：总额，即最终优惠后的金额，|
	CustomerBalances *[]CustomerBalancesV2 `json:"customer_balances,omitempty"`
}

func (o ListCustomersBalancesDetailResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListCustomersBalancesDetailResponse", string(data)}, " ")
}
