/*
 * CSBPartnerOpenAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type SendSmsVerificationCodeResponse struct {
}

func (o SendSmsVerificationCodeResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"SendSmsVerificationCodeResponse", string(data)}, " ")
}
