/*
 * TMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Request Object
type CreatePredefineTagsRequest struct {
	Body *ReqCreatePredefineTag `json:"body,omitempty"`
}

func (o CreatePredefineTagsRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreatePredefineTagsRequest", string(data)}, " ")
}
