/*
    * TMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type UpdatePredefineTagsRequest struct {
	Body *ModifyPrefineTag `json:"body,omitempty"`
}
