/*
    * TMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ShowApiVersionResponse struct {
	Version *VersionDetail `json:"version,omitempty"`
}
