/*
 * TMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type CreatePredefineTagsResponse struct {
	HttpStatusCode int `json:"-"`
}

func (o CreatePredefineTagsResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreatePredefineTagsResponse", string(data)}, " ")
}
