/*
    * TMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 修改预定义标签
type ModifyPrefineTag struct {
	NewTag *PredefineTagRequest `json:"new_tag"`
	OldTag *PredefineTagRequest `json:"old_tag"`
}
