/*
 * TMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 修改预定义标签
type ModifyPrefineTag struct {
	NewTag *PredefineTagRequest `json:"new_tag"`
	OldTag *PredefineTagRequest `json:"old_tag"`
}

func (o ModifyPrefineTag) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ModifyPrefineTag", string(data)}, " ")
}
