/*
    * TMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// 创建预定义标签请求
type ReqCreatePredefineTag struct {
	// 操作标识（区分大小写）：create（创建）
	Action string `json:"action"`
	// 标签列表
	Tags []PredefineTagRequest `json:"tags"`
}
