/*
 * TMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type UpdatePredefineTagsResponse struct {
}

func (o UpdatePredefineTagsResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdatePredefineTagsResponse", string(data)}, " ")
}
