/*
 * TMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// Response Object
type ListPredefineTagsResponse struct {
	// 分页位置标识（索引）。
	Marker string `json:"marker,omitempty"`
	// 查询到的标签总数
	TotalCount int32 `json:"total_count,omitempty"`
	// 查询到的标签列表
	Tags []PredefineTag `json:"tags,omitempty"`
}

func (o ListPredefineTagsResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListPredefineTagsResponse", string(data)}, " ")
}
