/*
    * TMS
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type ListPredefineTagsRequest struct {
	Key string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Marker string `json:"marker,omitempty"`
	OrderField string `json:"order_field,omitempty"`
	OrderMethod string `json:"order_method,omitempty"`
}
