/*
 * TMS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"
	"strings"
)

// 删除预定义标签请求
type ReqDeletePredefineTag struct {
	// 操作标识（区分大小写）：delete（删除）
	Action ReqDeletePredefineTagAction `json:"action"`
	// 标签列表
	Tags []PredefineTagRequest `json:"tags"`
}

func (o ReqDeletePredefineTag) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ReqDeletePredefineTag", string(data)}, " ")
}

type ReqDeletePredefineTagAction struct {
	value string
}

type ReqDeletePredefineTagActionEnum struct {
	DELETE ReqDeletePredefineTagAction
}

func GetReqDeletePredefineTagActionEnum() ReqDeletePredefineTagActionEnum {
	return ReqDeletePredefineTagActionEnum{
		DELETE: ReqDeletePredefineTagAction{
			value: "delete",
		},
	}
}

func (c ReqDeletePredefineTagAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(c.value)
}

func (c *ReqDeletePredefineTagAction) UnmarshalJSON(b []byte) error {
	c.value = string(strings.Trim(string(b[:]), "\""))
	return nil
}
