/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListInstanceMetricRequest struct {
	BlockchainId string                         `json:"blockchain_id"`
	Body         *ListInstanceMetricRequestBody `json:"body,omitempty"`
}

func (o ListInstanceMetricRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListInstanceMetricRequest", string(data)}, " ")
}
