/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type DownloadBlockchainCertResponse struct {
	HttpStatusCode int `json:"-"`
}

func (o DownloadBlockchainCertResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DownloadBlockchainCertResponse", string(data)}, " ")
}
