/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// 添加节点和添加组织，添加组织是需要提供pvc_name
type UpdateInstanceRequestBody struct {
	// 添加节点的组织列表
	NodeOrgs *[]NodeOrgs `json:"node_orgs,omitempty"`
}

func (o UpdateInstanceRequestBody) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"UpdateInstanceRequestBody", string(data)}, " ")
}
