/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// CCE组件
type ComCce struct {
	Cluster       *Detail `json:"cluster,omitempty"`
	Network       *Detail `json:"network,omitempty"`
	SecurityGroup *Detail `json:"security_group,omitempty"`
}

func (o ComCce) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ComCce", string(data)}, " ")
}
