/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DownloadBlockchainSdkConfigRequest struct {
	BlockchainId string          `json:"blockchain_id"`
	Body         *CfgRequestBody `json:"body,omitempty"`
}

func (o DownloadBlockchainSdkConfigRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DownloadBlockchainSdkConfigRequest", string(data)}, " ")
}
