/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListMembersRequest struct {
}

func (o ListMembersRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListMembersRequest", string(data)}, " ")
}
