/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type DeleteBlockchainRequest struct {
	BlockchainId    string `json:"blockchain_id"`
	IsDeleteStorage bool   `json:"is_delete_storage"`
	IsDeleteObs     *bool  `json:"is_delete_obs,omitempty"`
}

func (o DeleteBlockchainRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"DeleteBlockchainRequest", string(data)}, " ")
}
