/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type BatchAddPeersToChannelRequest struct {
	BlockchainId string                             `json:"blockchain_id"`
	Body         *BatchAddPeersToChannelRequestBody `json:"body,omitempty"`
}

func (o BatchAddPeersToChannelRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"BatchAddPeersToChannelRequest", string(data)}, " ")
}
