/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

type IefNode struct {
	// 节点ID
	Id *string `json:"id,omitempty"`
	// 节点状态
	Status *string `json:"status,omitempty"`
	// 节点公有IP
	PublicIpAddress *string `json:"public_ip_address,omitempty"`
}

func (o IefNode) String() string {
	data, err := json.Marshal(o)
	if err != nil {
		return "IefNode struct{}"
	}

	return strings.Join([]string{"IefNode", string(data)}, " ")
}
