/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

type HandleNotificationInvitor struct {
	// 邀请方实例id
	InvitorBcsId *string `json:"invitor_bcs_id,omitempty"`
	// 邀请方project id
	InvitorProjectId *string `json:"invitor_project_id,omitempty"`
	// 邀请方租户名
	InvitorUsername *string `json:"invitor_username,omitempty"`
}

func (o HandleNotificationInvitor) String() string {
	data, err := json.Marshal(o)
	if err != nil {
		return "HandleNotificationInvitor struct{}"
	}

	return strings.Join([]string{"HandleNotificationInvitor", string(data)}, " ")
}
