/*
 * BCS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type HandleNotificationRequest struct {
	Body *HandleNotificationRequestBody `json:"body,omitempty"`
}

func (o HandleNotificationRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"HandleNotificationRequest", string(data)}, " ")
}
