/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type StartInstanceRequest struct {
	InstanceId string `json:"instance_id"`
}
