/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type StacksAttribute struct {
	// 规格列表
	Specs []string `json:"specs,omitempty"`
	// 提示id
	Suggest string `json:"suggest,omitempty"`
	// 提示信息
	SuggestTitle string `json:"suggest_title,omitempty"`
	// 卷容量列表
	Volumes []string `json:"volumes,omitempty"`
}
