/*
 * cloudide
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type ListInstancesResponse struct {
	Instances *PageInstancesVo `json:"instances,omitempty"`
	// 状态
	Status *string `json:"status,omitempty"`
}

func (o ListInstancesResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListInstancesResponse", string(data)}, " ")
}
