/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type StartInstanceResponse struct {
	// 返回值
	Result string `json:"result,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
}
