/*
 * CloudIDE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type StartInstanceRequest struct {
	InstanceId string `json:"instance_id"`
}

func (o StartInstanceRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"StartInstanceRequest", string(data)}, " ")
}
