/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type CreateInstanceBy3rdResponse struct {
	Result *InstancesVo `json:"result,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
}
