/*
 * cloudide
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Response Object
type StopInstanceResponse struct {
	// 返回值
	Result *bool `json:"result,omitempty"`
	// 状态
	Status *string `json:"status,omitempty"`
}

func (o StopInstanceResponse) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"StopInstanceResponse", string(data)}, " ")
}
