/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type SourceStorage struct {
	// 位置
	Location string `json:"location,omitempty"`
	// 参数值
	Parameters map[string]string `json:"parameters,omitempty"`
	// 类型
	Type string `json:"type,omitempty"`
}
