/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CreateInstanceBy3rdRequest struct {
	InstanceLabel string `json:"instance_label,omitempty"`
	Body *InstanceEdgeParam `json:"body,omitempty"`
}
