/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type CreateInstanceRequest struct {
	OrgId string `json:"org_id"`
	Body *InstanceParam `json:"body,omitempty"`
}
