/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Request Object
type UpdateInstanceRequest struct {
	InstanceId string `json:"instance_id"`
	Body *InstanceUpdateParam `json:"body,omitempty"`
}
