/*
 * CloudIDE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type CreateInstanceRequest struct {
	OrgId string         `json:"org_id"`
	Body  *InstanceParam `json:"body,omitempty"`
}

func (o CreateInstanceRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"CreateInstanceRequest", string(data)}, " ")
}
