/*
 * cloudide
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ShowPriceRequest struct {
}

func (o ShowPriceRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ShowPriceRequest", string(data)}, " ")
}
