/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ShowPriceResponse struct {
	// 技术栈价格列表
	Prices []ResourcePrice `json:"prices,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
}
