/*
 * cloudide
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

package model

import (
	"encoding/json"

	"strings"
)

// Request Object
type ListProjectTemplatesRequest struct {
	Arch    *string `json:"arch,omitempty"`
	StackId string  `json:"stack_id"`
}

func (o ListProjectTemplatesRequest) String() string {
	data, _ := json.Marshal(o)
	return strings.Join([]string{"ListProjectTemplatesRequest", string(data)}, " ")
}
