/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

type Role struct {
	// 子角色
	CRole string `json:"c_role,omitempty"`
	// id
	Id string `json:"id,omitempty"`
	// 角色
	Role string `json:"role,omitempty"`
	// 角色执行操作列表
	RoleActionses []RoleAction `json:"role_actionses,omitempty"`
}
