/*
    * cloudide
    *
    * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    *
*/

package model

// Response Object
type ShowInstanceResponse struct {
	Instance *InstancesVo `json:"instance,omitempty"`
	// 状态
	Status string `json:"status,omitempty"`
}
