name: Go CI

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
permissions:
  contents: read
jobs:
  test:  
    runs-on: ubuntu-22.04
    strategy:  
      matrix:  
        go-version: ['1.14', '1.15', '1.16', '1.17', '1.18', '1.19', '1.20', '1.21', '1.22']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go-version }} 
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }} 
    - name: Build
      run: go mod tidy && go build ./...
    - name: Test
      run: go test ./core/... -v -cover
